spring:
  r2dbc:
    url: r2dbc:postgresql://localhost:5432/kominioai_bulletin_dev
    username: postgres
    password: password

  flyway:
    url: jdbc:postgresql://localhost:5432/kominioai_bulletin_dev
    user: postgres
    password: password

logging:
  level:
    root: INFO
    com.kominioai.domain.bulletin: DEBUG
    org.springframework.r2dbc: DEBUG
    org.springframework.security: DEBUG
    org.springframework.web: DEBUG

bulletin:
  config:
    debug: true
    mock-data: true
