version: "3.8"

services:
  mariadb:
    build:
      context: infra/mariadb_lky
    container_name: mariadb_komroonga
    restart: unless-stopped
    environment:
      MARIADB_ROOT_PASSWORD: 1234
      MARIADB_DATABASE: db_dev
      MARIADB_USER: leekyroot
      MARIADB_PASSWORD: 1234
    ports:
      - "3306:3306"
    volumes:
      - mariadb_1_data:/var/lib/mysql
    networks:
      - mariadb_network

  redis_1:
    image: redis:latest
    container_name: redis_1
    restart: unless-stopped
    ports:
      - "6379:6379"
    volumes:
      - redis_1_data:/data
    networks:  # Redis에도 네트워크 추가
      - mariadb_network

volumes:
  mariadb_1_data:
  redis_1_data:

networks:
  mariadb_network:
    driver: bridge