version: '3.8'

services:
  mariadb:
    build:
      context: infra/mariadb_lky
    container_name: mariadb_komroonga
    restart: unless-stopped
    environment:
      MARIADB_ROOT_PASSWORD: 1234
      MARIADB_DATABASE: db_dev
      MARIADB_USER: leekyroot
      MARIADB_PASSWORD: 1234
    ports:
      - "3306:3306"
    volumes:
      - mariadb_1_data:/var/lib/mysql  # 데이터 영속화 볼륨

volumes:
  mariadb_1_data: