CREATE TABLE users (
                       id VARCHAR(36) PRIMARY KEY,
                       email VARCHAR(255) UNIQUE NOT NULL,
                       password_hash VARCHAR(255) NOT NULL,
                       username VARCHAR(100) UNIQUE NOT NULL,
                       first_name VARCHAR(100),
                       last_name VARCHAR(100),
                       profile_image_url VARCHAR(500),
                       phone VARCHAR(20),
                       account_status VARCHAR(20) NOT NULL DEFAULT 'ACTIVE',
                       email_verified BOOLEAN NOT NULL DEFAULT FALSE,
                       email_verification_token VARCHAR(255),
                       email_verification_expires_at TIMESTAMP,
                       password_reset_token VARCHAR(255),
                       password_reset_expires_at TIMESTAMP,
                       last_login_at TIMESTAMP,
                       failed_login_attempts INT DEFAULT 0,
                       account_locked_until TIMESTAMP,
                       two_factor_enabled BOOLEAN NOT NULL DEFAULT FALSE,
                       two_factor_secret VARCHAR(255),
                       created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
                       updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,

                       INDEX idx_users_email (email),
                       INDEX idx_users_username (username),
                       INDEX idx_users_account_status (account_status),
                       INDEX idx_users_email_verified (email_verified),
                       INDEX idx_users_created_at (created_at)
);