export type WebMediaMessageType =
  | 'JoinRequest'
  | 'JoinResponse'
  | 'ErrorResponse'
  | 'UserJoinedEvent'
  | 'UserLeftEvent'
  | 'UserStateChangedEvent'
  | 'UserPublishedChangeReport'
  | 'StreamRepublishedReport'
  | 'UserStreamRepublishedEvent'
  | 'UserKickedEvent'
